# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Action JS Template'
description: 'A simple javascript template for rapid development of GitHub actions.'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
    ACTIONS_RUNNER_DEBUG: true
    # ACTIONS_STEP_DEBUG: true


  deepL_input: # id of input
    required: true
    default: 'default value'

outputs:
 result: # id of output
   description: "output"

runs:
  using: 'node12'
  main: 'dist/index.js'
