name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: a test module
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: install
        run: yarn install
      
      - name: format-check
        run: yarn format-check

      - name: package
        run: yarn package

      - name: module running action step
        id: input_testing
        uses: DaisukeMiyazaki/deepL_translations@1-test
        with:
          input_testing: "Daisuke Miyazaki"

      - name: Get the output time
        run: echo "the time was $ {{ steps.input_testing.outputs.time }}"