name: CI

on:
  issue_comment:
    types: [edited]

jobs:
  setup:
    if: contains(github.event.comment.reactions.rocket, 1)
    runs-on: ubuntu-latest
    name: deepl_tranlation integration
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install
        run: yarn install

      - name: format-check
        run: yarn format-check

      - name: package
        run: yarn package

      - name: module running step
        uses: ./ # this is for private repo
        id: deepL_input
        with:
          deepL_input: ${{ github.event.comment.body }}
        env: 
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        # uses: DaisukeMiyazaki/deepL_translations@main # disable this for private repo

      - name: read comment body
        run: |
          echo ${{ github.event.comment.body }}
          echo ${{ github.event.changes.body.from }}
          echo "the translated result was ${{ steps.deepL_input.outputs.deepL_output_success }}"

      - name: insert comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "auto_translated: ${{ steps.deepL_input.outputs.deepL_output_success }}"
            })
