name: CI

on:
  issue_comment:
    types: [created, edited]

jobs:
  setup:
    if: contains(github.event.comment.reactions.rocket, 1)
    runs-on: ubuntu-latest
    name: a test module
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install
        run: yarn install

      - name: format-check
        run: yarn format-check

      - name: package
        run: yarn package

      - name: module running action step
        uses: ./ # this is for private repo
        id: input_testing
        with:
          input_testing: ${{ github.event.comment.body }}
        env: 
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        # uses: DaisukeMiyazaki/deepL_translations@main # disable this for private repo

      - name: Get the output time
        run: |
          echo "the time was ${{ steps.input_testing.outputs.time }}"
          echo "the translated result was ${{ steps.input_testing.outputs.success }}"

      - name: read comment body
        run: |
          echo ${{ github.event.comment.body }}
          echo ${{ github.event.changes.body.from }}

      - name: insert comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "this is a test comment inserting to wherever"
            })
